#!/bin/bash

#create aliases
printf "alias ls='exa -F'
alias lsa='exa -aF'
alias l='exa -1F --icons'
alias la='exa -1aF --icons'
alias ll='exa -lhumF --icons'
alias lla='exa -lhFa --icons'
alias lt='exa -F -L 2 --tree --icons'
alias ltd='exa -DF --tree --icons'
alias ltt='exa -F --tree --icons'
alias lta='exa -aF --tree --icons'
alias llt='exa -lhumF -L 2 --tree --icons'
alias lltt='exa -lF --tree --icons'
alias llta='exa -laF --tree'
alias dsa='du -ah --max-depth=1'
alias tua='ss -tua'
alias ip='ip --color'
alias cls='clear'
alias dir='exa -F'
alias duf='duf -hide special'
alias ECHO='echo'
alias neofetch='neofetch --color_blocks off'" \
| tee -a $HOME/.bashrc >> $HOME/.zshrc

#turn on cdspell for bash, plus autocorrection and case-insensitive cd for zsh
printf "shopt -s cdspell" >> $HOME/.bashrc
printf "setopt correct" >> $HOME/.zshrc
printf "function cd() {
        dir_found=false
        if (builtin cd $1 2> /dev/null) 
        then
                builtin cd $1
                dir_found=true
        else
        directories=($(find . -maxdepth 1 -type d | sed -e 's|\./||'))
        for dir in ${directories[@]}
        do
                if [[ ${(L)dir} == ${(L)1} ]]; then
                echo $dir
                builtin cd $dir
                dir_found=true
                fi
        done
        fi
        [[ $dir_found != true ]] && echo "cd: no such file or directory: $1"
}" >> $HOME/.zshrc