#!/bin/bash

#update if needed
sudo pacman -Syu || exit 1
#install zsh
which zsh || sudo pacman -S zsh
#install utilities
which exa || sudo pacman -S exa & \
which bat || sudo pacman -S bat & \
which duf || sudo pacman -S duf & \
which rg || sudo pacman -S ripgrep & \
which fzf || sudo pacman -S fzf & \ 
which neofetch || sudo pacman -S neofetch & \
which glances || sudo pacman -S glances
which arp || sudo pacman -S net-tools
which dig || sudo pacman -S extra/bind
#install text editors and enable nano syntax highlighting
which nano || sudo pacman -S nano && find /usr/share/nano/ -iname "*.nanorc" -exec echo include {} \; >> ~/.nanorc
which vim || sudo pacman -S vim & \
which emacs || sudo pacman -S emacs-nox

printf "runtime defaults.vim
set tabstop=4
set shiftwidth=4" > ~/.vimrc

#install trizen AUR package manager
sudo pacman -Sy --needed base-devel git 
if ! which trizen; then
    git clone https://aur.archlinux.org/trizen.git
    cd trizen
    makepkg -si
    cd ..
fi

#install wttr front-end tool
which wttr || sudo curl -o /usr/local/bin/wttr https://raw.githubusercontent.com/pingej77/wttr/main/wttr && sudo chmod +x /usr/local/bin/wttr
#install net info
which netinfo || sudo curl -o /usr/local/bin/netinfo https://raw.githubusercontent.com/pingej77/netinfo/main/netinfo && sudo chmod +x /usr/local/bin/netinfo

#!/bin/bash

#create aliases
printf "alias ls='exa -F'
alias lsa='exa -aF'
alias l='exa -1F --icons'
alias la='exa -1aF --icons'
alias ll='exa -lhumF --icons'
alias lla='exa -lhFa --icons'
alias lt='exa -F -L 2 --tree --icons'
alias ltd='exa -DF --tree --icons'
alias ltt='exa -F --tree --icons'
alias lta='exa -aF -L 2 --tree --icons'
alias llt='exa -lhumF -L 2 --tree --icons'
alias lltt='exa -lF --tree --icons'
alias llta='exa -laF -L 2 --tree'
alias ltta='exa -aF --tree --icons'
alias lltta='exa -laF --tree'
alias dsa='du -ah --max-depth=1'
alias tua='ss -tua'
alias ip='ip --color'
alias cls='clear'
alias dir='exa -F'
alias duf='duf -hide special'
alias ECHO='echo'
alias ping='ping -c 3'
alias PING='ping'
alias neofetch='neofetch --color_blocks off'" \
| tee -a $HOME/.bashrc >> $HOME/.zshrc

#turn on cdspell for bash, plus autocorrection and case-insensitive cd for zsh
printf "shopt -s cdspell" >> $HOME/.bashrc
printf "setopt correct" >> $HOME/.zshrc
cat << 'EOT' >> $HOME/temptest
function cd() {
        dir_found=false
        if (builtin cd $1 2> /dev/null) 
        then
                builtin cd $1
                dir_found=true
        else
        IFS=$'\n'
		directories=($(find . -maxdepth 1 -type d | sed -e 's|\./||'))
        IFS=' '
		for dir in ${directories[@]}
        do
                if [[ ${(L)dir} == ${(L)*} ]]; then
                echo "$dir"
                builtin cd "$dir"
                dir_found=true
                fi
        done
        fi
        [[ $dir_found != true ]] && echo "cd: no such file or directory: $*
} 
EOT

